announcement:
    enable: true
    interval: 30
    groups:
        default:
        - "&1This is a test announcement"
        - "&cC&6O&aL&bO&9U&5R&1!"
        owner:
        - "Special announcement"
        - "Only Owners can see this xD"
randomteleport:
    enable: true
    cooldown: 10
    replenishUses: true
    timeToReplenishUses: 40
    maxUses: 3
    worlds:
        world:
            centerX: 0
            centerZ: 0
            maxRange: 10